services:
  - type: web
    name: npcchatter-backend
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app -b 0.0.0.0:$PORT
    plan: free
    autoDeploy: true
    envVars:
      - key: APP_ENV
        value: production

  - type: web
    runtime: static
    name: npcchatter-frontend
    rootDir: frontend
    buildCommand: npm ci && npm run build
    staticPublishPath: dist
    pullRequestPreviewsEnabled: true
    autoDeploy: true
    envVars:
      - key: VITE_API_BASE
        fromService:
          type: web
          name: npcchatter-backend
          property: url