# render.yaml
services:
  # --- Backend (Flask) ---
  - type: web
    runtime: python
    name: npcchatter-backend
    rootDir: backend
    autoDeployTrigger: commit
    buildCommand: pip install -r requirements.txt
    # If your Flask app object is `app` in backend/app.py, this is correct:
    startCommand: gunicorn -k eventlet -w 1 app:app -b 0.0.0.0:$PORT
    envVars:
      - key: APP_ENV
        value: production
      - key: ALLOWED_ORIGINS
        value: |
          https://npcchatter.com,
          https://www.npcchatter.com
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        sync: false
      - key: JWT_SECRET
        sync: false

  # --- Frontend (Static Site) ---
  - type: web
    runtime: static
    name: npcchatter-frontend
    rootDir: frontend
    autoDeployTrigger: commit
    previews:
      generation: automatic
    buildCommand: npm ci && npm run build
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: '/*'
        destination: '/index.html'
    # NOTE: domains removed to avoid "already taken" blueprint error.
    envVars:
      - key: VITE_API_BASE
        # Use the backend's public URL. Replace after first deploy if needed.
        value: https://npcchatter-backend.onrender.com