services:
  - type: web
    name: npcchatter-backend
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -k eventlet -w 1 app:app -b 0.0.0.0:$PORT
    plan: free
    autoDeploy: true
    envVars:
      - key: APP_ENV
        value: production
      - key: ALLOWED_ORIGINS
        fromService:
          type: web
          name: npcchatter-frontend
          property: host
      - key: DATABASE_URL
        value: ""
      - key: REDIS_URL
        value: ""
      - key: JWT_SECRET
        value: ""

  - type: static
    name: npcchatter-frontend
    rootDir: frontend
    buildCommand: npm ci && npm run build
    staticPublishPath: dist
    pullRequestPreviewsEnabled: true
    autoDeploy: true
    routes:
      - type: rewrite
        source: '/*'
        destination: '/index.html'
    domains:
      - www.npcchatter.com
      - npcchatter.com
    envVars:
      - key: VITE_API_BASE
        fromService:
          type: web
          name: npcchatter-backend
          property: host