name: CI - build frontend & check backend

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install & build frontend
        working-directory: frontend
        run: |
          npm ci
          npm run build

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install backend requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt

      - name: Check backend Python compiles
        run: |
          python -m py_compile backend/app.py backend/test_redis.py || true

      - name: Upload build artifacts (frontend dist)
        uses: actions/upload-artifact@v4
        with:
          name: frontend-dist
          path: frontend/dist
